# Generated by Django 3.2.5 on 2022-07-02 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50, unique=True)),
                ('position_details', models.TextField(max_length=200, null=True)),
                ('base_salary', models.PositiveIntegerField()),
                ('tada', models.FloatField(default=10000, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
    ]
