# Generated by Django 3.2.5 on 2022-07-02 04:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payapp', '0002_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pf_percent', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(20.0)])),
                ('strip_account_id', models.CharField(max_length=100)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payapp.accountant')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payapp.position')),
            ],
        ),
    ]
