# Generated by Django 3.2.5 on 2022-07-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0003_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='strip_account_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
