# Generated by Django 3.2.5 on 2022-07-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payapp', '0004_alter_employee_strip_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountant',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
